include:
    - local: /.gitlab-ci/common.yaml

variables:
  K8S_API_LOGIN_URL: "https://api.conducktor.t-mobile.com/api/v3/login?provider=conducktor"
  K8S_SERVER_URL: "https://west.stg.duck.master.kube.t-mobile.com:6443"
  K8S_CLUSTER: "duck-stg-w2"
  K8S_DOMAIN: "$K8S_CLUSTER.kube.t-mobile.com"
  K8S_NS: "hld-stg-duck-stg-w2"
  HELM_APP_NAME: $CI_PROJECT_NAME
  EXTERNAL_DNS_TARGET: "internal-stg-k8s-duck-ing-int-w2-327646687.us-west-2.elb.amazonaws.com"
  K8S_DEPLOY_STRATEGY: "BLUE_GREEN"

# Deploy on Conducktor Namespace (hld-stg-duck-stg-w2)
duck-stg-w2-deploy:
  stage: deploy
  extends: .helm_deploy
  variables:
     FLAGGER_MONITORING: "true"
     FLG_CANARY_MOINITOR_DURATION_SECS: "150"
  environment:
    name: stg/$K8S_CLUSTER/smoke
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME

validate_duck-stg-w2-deploy:
  stage: post-deploy
  extends: .validate_app
  needs: ["duck-stg-w2-deploy"]
  dependencies: ["duck-stg-w2-deploy"]

duck-stg-w2-promote:
  stage: promote
  extends: .k8s_promote_app
  variables:
     FLAGGER_MONITORING: "true"
     FLG_CANARY_MOINITOR_DURATION_SECS: "150"
  needs: ["duck-stg-w2-deploy","validate_duck-stg-w2-deploy"]
  dependencies: ["duck-stg-w2-deploy","validate_duck-stg-w2-deploy"]
  environment:
    name: stg/$K8S_CLUSTER/smoke
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

duck-stg-w2-sanity:
  extends: .sanity
  needs: ["duck-stg-w2-deploy","duck-stg-w2-promote"]
  dependencies: ["duck-stg-w2-deploy","duck-stg-w2-promote"]
  environment:
    name: stg/$K8S_CLUSTER/smoke
    action: verify
  retry: 1

validate_duck-stg-w2-promote:
  variables:
    VALIDATE_PHASE: "PROMOTION"
  stage: verify
  extends: .validate_app
  needs: ["duck-stg-w2-deploy","duck-stg-w2-promote"]
  dependencies: ["duck-stg-w2-deploy","duck-stg-w2-promote"]

duck-stg-w2-rollback:
  stage: rollback
  extends: .helm_rollback
  environment:
    name: stg/$K8S_CLUSTER/smoke
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME
  needs: ["validate_duck-stg-w2-promote"]
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

validate_duck-stg-w2-rollback:
  variables:
    VALIDATE_PHASE: "ROLLBACK"
  stage: verify-rollback
  extends: .validate_app
  needs: ["duck-stg-w2-rollback"]
