include:
    - local: /.gitlab-ci/common.yaml

variables:
  K8S_API_LOGIN_URL: "https://api.conducktor.t-mobile.com/api/v3/login?provider=conducktor"
  K8S_SERVER_URL: "https://west.stg.duck.master.kube.t-mobile.com:6443"
  K8S_NS: "hld-stg-duck-stg-w2"
  EXTERNAL_DNS_TARGET: "internal-stg-k8s-duck-ing-int-w2-327646687.us-west-2.elb.amazonaws.com"
  CANARY_INTERVAL: "90s"

# Deploy on Conducktor Namespace (hld-stg-duck-stg-w2)
duck-stg-deploy:
  stage: deploy
  extends: .helm_deploy
  variables:
     FLAGGER_MONITORING: "true"
  environment:
    name: prod_staging/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME

validate_duck-stg-deploy:
  stage: post-deploy
  extends: .validate_app
  needs: ["duck-stg-deploy"]
  dependencies: ["duck-stg-deploy"]

duck-stg-promote:
  stage: promote
  extends: .k8s_promote_app
  variables:
     FLAGGER_MONITORING: "true"
  needs: ["duck-stg-deploy","validate_duck-stg-deploy"]
  dependencies: ["duck-stg-deploy","validate_duck-stg-deploy"]
  environment:
    name: prod_staging/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

duck-stg-sanity:
  extends: .sanity
  needs: ["duck-stg-deploy","duck-stg-promote"]
  dependencies: ["duck-stg-deploy","duck-stg-promote"]
  environment:
    name: prod_staging/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    action: verify
  retry: 1
  when: delayed
  start_in: 90 seconds

validate_duck-stg-promote:
  variables:
    VALIDATE_PHASE: "PROMOTION"
  stage: verify
  extends: .validate_app
  needs: ["duck-stg-deploy","duck-stg-promote"]
  dependencies: ["duck-stg-deploy","duck-stg-promote"]

duck-stg-rollback:
  stage: rollback
  extends: .helm_rollback
  variables:
     FLAGGER_MONITORING: "true"
  environment:
    name: prod_staging/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME
  needs: ["validate_duck-stg-promote"]
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

validate_duck-stg-rollback:
  variables:
    VALIDATE_PHASE: "ROLLBACK"
  stage: verify-rollback
  extends: .validate_app
  needs: ["duck-stg-rollback"]
