include:
    - local: /.gitlab-ci/common.yaml

variables:
  K8S_NS: "hld-plb-duck-plb-w2"
  K8S_API_LOGIN_URL: "https://api.conducktor.t-mobile.com/api/v3/login?provider=conducktor"
  K8S_SERVER_URL: "https://west.plb.duck.master.kube.t-mobile.com:6443"
  EXTERNAL_DNS_TARGET: "internal-plb-k8s-duck-ing-int-w2-517343465.us-west-2.elb.amazonaws.com"
  CANARY_INTERVAL: "50s"
  SYNTHETIC_TEST_HEY_CMD_ARGS: "-z 30s -q 15 -c 2"
  TLS_ENABLED: "true"

# Deploy on conducktor namespace (hld-plb-duck-plb-w2)
duck-plb-deploy:
  stage: deploy 
  extends: .helm_deploy
  variables:
     FLAGGER_MONITORING: "true"
     CANARY_PROMOTION_AUTO: "true"
  environment:
    name: prod/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: production
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME

duck-plb-sanity:
  extends: .sanity
  needs: ["duck-plb-deploy"]
  dependencies: ["duck-plb-deploy"]
  environment:
    name: prod/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    action: verify
  retry: 1
  when: delayed
  start_in: 90 seconds

validate_duck-plb-deploy:
  variables:
    VALIDATE_PHASE: "PROMOTION"
  stage: verify
  extends: .validate_app
  needs: ["duck-plb-deploy"]
  dependencies: ["duck-plb-deploy"]

duck-plb-rollback:
  stage: rollback
  extends: .helm_rollback
  variables:
     FLAGGER_MONITORING: "true"
  environment:
    name: prod/$K8S_CLUSTER/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: production
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME
  needs: ["validate_duck-plb-deploy"]
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

validate_duck-plb-rollback:
  variables:
    VALIDATE_PHASE: "ROLLBACK"
  stage: verify-rollback
  extends: .validate_app
  needs: ["duck-plb-rollback"]
