include:
    - local: /.gitlab-ci/common.yaml

variables:
  K8S_API_LOGIN_URL: "https://api.conducktor.t-mobile.com/api/v3/login?provider=conducktor"
  K8S_SERVER_URL: "https://west.dev.duck.master.kube.t-mobile.com:6443"
  K8S_NS: "hld-dev-duck-dev-w2"
  EXTERNAL_DNS_TARGET: "internal-dev-k8s-duck-ing-int-w2-1678771246.us-west-2.elb.amazonaws.com"

# Deploy on Conducktor namespace ( hld-dev-duck-dev-w2 )
duck-rev-deploy:
  stage: deploy
  extends: .helm_deploy
  variables:
    AUTO_SCALING: "true"
  resource_group: $K8S_CLUSTER-$HELM_APP_NAME
  environment:
    name: review/$K8S_CLUSTER/$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: development
    on_stop: duck-rev-stop
    auto_stop_in: 2 days

duck-rev-sanity:
  extends: .sanity
  needs: ["duck-rev-deploy"]
  dependencies: ["duck-rev-deploy"]
  retry: 1
  when: delayed
  start_in: 3 minutes
  environment:
    name: review/$K8S_CLUSTER/$HELM_APP_NAME
    action: verify

duck-rev-stop:
  needs: ["duck-rev-deploy"]
  extends: .k8s_teardown
  resource_group: $K8S_CLUSTER-$HELM_APP_NAME
  environment:
    name: review/$K8S_CLUSTER/$HELM_APP_NAME
    action: stop
    deployment_tier: development
  rules:
    - when: manual
      allow_failure: true
