apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helloworld.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helloworld.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: app-logs
          hostPath:
            path: /var/log/
            type: Directory
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            failureThreshold: {{ .Values.service.healthCheck.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.service.healthCheck.readinessProbe.path }}
              port: {{ .Values.service.port }}
              scheme: {{ .Values.service.healthCheck.scheme }}
            initialDelaySeconds: {{ .Values.service.healthCheck.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.healthCheck.readinessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: {{ .Values.service.healthCheck.timeoutSeconds }}
          livenessProbe:
            failureThreshold: {{ .Values.service.healthCheck.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.service.healthCheck.livenessProbe.path }}
              port: {{ .Values.service.port }}
              scheme: {{ .Values.service.healthCheck.scheme }}
            initialDelaySeconds: {{ .Values.service.healthCheck.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.service.healthCheck.livenessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: {{ .Values.service.healthCheck.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs/
          env:
           - name: TARGET_SERVER_URL
             value: {{ .Values.service.targetUrl | quote }}
           - name: ENVIRONMENT
             value: {{ .Values.service.environment | quote }}
           - name: PIPELINE_ID
             value: {{ int64 .Values.service.pipelineId | quote }}
           - name: PIPELINE_URL
             value: {{ .Values.service.pipelineUrl | quote }}
           - name: COMMIT_SHA
             value: {{ .Values.service.commitSha | quote }}
           - name: APP_NAME
             value: {{ .Values.service.appName | quote }}
           - name: DEPLOYED_BY
             value: {{ .Values.service.deployedBy | quote }}
           - name: DEPLOYED_VERSION
             value: {{ .Values.service.deployedVersion | quote }}
           - name: COMMIT_USER
             value: {{ .Values.service.commitUser | quote }}
           - name: COMMIT_TS
             value: {{ .Values.service.commitTs | quote }}
           - name: COMMIT_BRANCH
             value: {{ .Values.service.commitBranch | quote }}
           - name: DEPLOY_STRATEGY
             value: {{ .Values.service.deployStrategy | quote }}
           - name: DEPLOY_PLATFORM
             value: {{ .Values.service.deployPlatform | quote }}
           - name: NODE_NAME
             valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
           - name: POD_NAME
             valueFrom:
              fieldRef:
                fieldPath: metadata.name
           - name: POD_NAMESPACE
             valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
           - name: POD_IP
             valueFrom:
              fieldRef:
                fieldPath: status.podIP
           - name: POD_SERVICE_ACCOUNT
             valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
           - name: POD_HOST_IP
             valueFrom:
              fieldRef:
                fieldPath: status.hostIP
      imagePullSecrets:
          - name: {{ .Values.imagePullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
