# Injection of templates
include:
  # Injects TMO Global Shared (handles certs, lists blacklisted files etc.)  
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.global.common.gitlab-ci.yml'
    
  # Injects Maven Test
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.job.mavenTest.gitlab-ci.yml'

  # Injects Maven Build
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.job.mavenBuild.gitlab-ci.yml'

  # Injects Maven Publish
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.job.mavenPublish.gitlab-ci.yml'
  
  # Inject Gitlab checks
  - template: SAST.gitlab-ci.yml

  # Injects SonarScan capability
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.job.sonar.gitlab-ci.yml'
    
  # Injects PCF Deploy function
  - project: 'tmobile/templates'
    ref: tmo/master
    file: '/gitlab-ci/.tmo.function.pcf.gitlab-ci.yml'

stages: 
  - tmo 
  - build
  - test
  - scan
  - publish
  - deploy

variables:
    # Common Parameters (used by build and deploy)
    APP_VERSION: "1.0"
    BUILD_NUMBER: "$CI_COMMIT_SHORT_SHA"
    
    # Maven Parameters
    MAVEN_PUBLISH_ARGS: "-Dfile=target/${CI_PROJECT_NAME}-${APP_VERSION}-$CI_COMMIT_SHORT_SHA.jar"
    
    # PCF Deploy Parameters
    PCF_API: "api.sys.px-npe01.cf.t-mobile.com"
    PCF_ORG: "enterprise-pipeline"

# Deploy to Development environment
deploy-dev:
  extends: .pcf-deploy
  except:
    - /^tmo\/.*$/
  environment:
    name: dev
  
# Deploy to Staging environment   
deploy-stg:
  extends: .pcf-deploy
  only:
    - /^tmo\/.*$/
  environment:
    name: stg    
  when: manual
   
# Deploy to Production environment    
deploy-prd:
  extends: .pcf-deploy
  only:
    - tmo/master
  environment:
    name: prd
  when: manual 