# Note: see https://docs.gitlab.com/ce/ci/yaml/README.html for all
# available options.

# Establish the order of the CI pipeline jobs.  This is a list of
# _stages_ for the whole pipeline, and the order here is the order in
# which the stages are run.
#
# Stage names are arbitrary, but we recommend the set shown here.
stages:
- test
- build
- package
- ci
- deploy-qa
- deploy-stg
- deploy-prod

# This section can contain variable values for all jobs.  (Individual
# jobs can also have a "variables" declaration, which can override
# values set up here.)  This is not the only place variables can be
# set; the gitlab UI also allows variables to be set, and that should
# be used for sensitive values, such as login passwords.
variables:
  APP_NAME: "edp-helloworld-rest"
  APP_VERSION: "1.0"
  BUILD_NUMBER: "$CI_COMMIT_SHORT_SHA"
  AUTOTAG_IMG: "registry.gitlab.com/tmobile/edp/autotag:latest"
  GITLAB_CORE_IMG: "registry.gitlab.com/tmobile/edp/gitlab-core:latest"

# This is a _job_, as opposed to a stage.  Multiple jobs can be in a
# given stage, in which case the jobs are run in parallel.
#
# Job names are also arbitrary, and need not match the stage names.
# If there is only one job in the stage, it's probably best to give it
# the same name as the stage; if there are multiple jobs, we suggest
# using the stage name as a prefix, e.g., "test-unit",
# "test-function", etc.
test:
  # Image to build with: contains Maven 3.3.9.
  image: maven:3.3.9

  # This job will be run in the "test" stage.
  stage: test

  # We don't want to run this job when a new tag is created.
  except:
  - tags

  # Shell script to run within the job.  In this case, we're doing a
  # single step--running Maven with the "test" target--but multiple
  # steps are possible; see the "package" job for an example.  The
  # list is executed in order.
  script:
  - mvn test -DAPP_VERSION=$APP_VERSION -DBUILD_NUMBER=$BUILD_NUMBER

  # This job happens to produce no artifacts we wish to save, but we
  # could do that; see the "build" job for an example of how to save
  # artifacts.

# This is a "build" job that produces an artifact.
build:
  image: maven:3.3.9
  stage: build
  except:
  - tags
  script:
  - mvn package -DAPP_VERSION=$APP_VERSION -DBUILD_NUMBER=$BUILD_NUMBER

  # Artifacts are named collections of files.  Here, we're giving this
  # artifact a name derived from the branch name and the commit SHA;
  # this name will be used as the name of the downloadable ZIP file
  # associated with the job.  Artifacts can be used by later stages.
  artifacts:
    # Name for the artifact.
    name: '$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA'

    # List of file globs that can be used to specify the files to
    # include in the artifact.  Here, we're only saving the built .jar
    # file, but additional files could be saved.
    paths:
    - target/*.jar

    # We can specify a maximum time for the artifact to be saved.
    # This specification will cause gitlab to delete the artifact
    # after 1 week.
    expire_in: 1 week

# This is a "package" job that builds a docker container image using
# the artifact that was created in the "build" job.
package:
  image: docker:latest
  stage: package

  # We only want to package up docker containers for our trunk
  # ("tmo/master") and release ("tmo/release-x.y") branches; this rule
  # accomplishes that by ensuring that the branch matches the given
  # regular expression.  Also note the "except", which ensures that
  # this job is not created or run when a tag is created.
  only:
  - /^tmo\/.*$/
  except:
  - tags

  # To build a docker image from a gitlab job, we need a "service".  A
  # number of services are already defined in gitlab, so we tell them
  # we need the "dind" service; that just stands for
  # "docker-in-docker", and is what allows building one docker
  # container from inside an executing container.  (Jobs in gitlab run
  # in isolated docker containers, not VMs.)
  services:
  - docker:dind

  # We also have to let docker know it should use the "overlay"
  # driver.  This is done through the environment variable
  # DOCKER_DRIVER.
  variables:
    DOCKER_DRIVER: overlay

  # These are the steps needed to construct the image.
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# This job is intended to run smoke tests on the constructed docker
# image, and is the first step in the deployment process.  The design
# chosen here is to start the built image as a service, then check
# that it responds to its HTTP endpoint appropriately.
ci:
  # We don't need Java or Maven here, so use a base image.
  image: busybox:latest
  stage: ci

  # Again, we only want to run this job on branches matching "tmo/*",
  # since "package" is a dependency and won't run on other branches.
  only:
  - /^tmo\/.*$/
  except:
  - tags

  # Here again we're using a service; but this time, it's not a
  # standard docker service--we're actually starting up the container
  # from the "package" job as a service.  That will spin up a
  # container for just this job, and we can run our smoke tests
  # against it.  Notice the use of "alias" here to ensure a hostname
  # we can predict for the wget in the script.
  services:
  - name: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    alias: helloworld

  # This script should be a series of simple smoke tests that just
  # validate that the image basically works.  In particular, extensive
  # or intensive testing probably shouldn't be done here; that should
  # be left to the dev, qa, and staging environments.
  script:
  - out=`wget -q -O- http://helloworld:19000/greeting?name=name` && [ "$out" == '{"id":1,"greeting":"Hello, name!"}' ]

# At the same time we're running the smoke tests, we also want to
# deploy our service to the dev environment.  This job is a stub for
# how to accomplish deployment.
deploy-dev:
  image: busybox:latest

  # Note that this job is also in the "ci" stage, meaning it will run
  # in parallel with the "ci" job shown above.  This happens to be the
  # only step in this example where we do this, but this feature could
  # be used to, for example, parallelize tests.
  stage: ci

  only:
  - /^tmo\/.*$/
  except:
  - tags

  # This is a stub for a deployment job, so right now it just contains
  # an "echo" statement.  Substitute the code you actually need to
  # deploy to your dev environment.
  script:
  - echo "Deploy to dev"

  # This section is specific to jobs that deploy to environments.  The
  # gitlab API can keep track of which SHA is running in which
  # environment, and this is how that happens.
  environment:
    name: dev

    # The gitlab UI can also have a button to go directly to a URL for
    # that environment.  This can be handy to try your UI code out and
    # see if it does what it was intended to do.  If your service has
    # a web-accessible UI, it might make sense to set this URL.  Our
    # example service doesn't have a web UI, so we don't set that
    # here...and of course, this job is just a stub, so it's not even
    # actually deployed anywhere anyway.
    #
    # If you are using this example and want to make use of this
    # feature, simply uncomment the line below and enter the correct
    # URL for this environment.  You can also set this in the
    # "environment" section of the other deploy jobs as well, though
    # this example .gitlab-ci.yml does not show this.
    #url: http://example.dev.t-mobile.com

# This is the first curated environment deployment job--in this case,
# to the QA environment.  It requires the user specifically click a
# button to perform the deployment.  Pipelines pause here; it is not
# allowed to deploy to the staging ("stg") environment unless the same
# code has already been deployed to the QA ("qa") environment, and
# certainly not to the production ("prod") environment.
#
# In addition to deploying to an environment, this job illustrates
# setting a tag.  We recommend setting "release candidate", or "rc",
# tags when deploying to the QA environment.
deploy-qa:
  image: $AUTOTAG_IMG
  stage: deploy-qa
  only:
  - /^tmo\/.*$/
  except:
  - tags

  # The gitlab-core service provides interfaces used by autotag to
  # perform the repository tag manipulation that it does.
  services:
  - name: $GITLAB_CORE_IMG
    alias: gitlab-core

  # Note: The design is to have the job set a tag of the form
  # "tmo/rc/NNN", where "NNN" is a number starting from one and
  # incrementing each time this job is triggered.  (There is also
  # support for using short-lived release branches, which require a
  # slightly different naming scheme: "tmo/rc/NNN.MMM".)
  #
  # The first step of the script is to invoke the autotag script.
  # This script automates the task of creating the tags described
  # above, but is extremely flexible; you may wish to check out if it
  # fits other tagging needs you may have.
  #
  # The next step is the actual deployment to the environment.  In
  # this case, it happens to be stubbed.
  script:
  - autotag incr
  - echo "Deploy to QA"

  # We use "qa" as the name of the environment to deploy to.
  environment:
    name: qa

  # These two settings make this job function manually, and prevent
  # the execution of the later jobs until this job has been executed,
  # respectively.
  when: manual
  allow_failure: false

# This job deploys to the staging environment.  This is the last step
# before code can be promoted into the production environment.  As
# with the deploy-qa job, pipelines pause here, and deployment to
# production cannot occur until this job has been executed.
#
# In addition to deploying to the staging environment, this job
# illustrates setting a "release" tag, which is recommended for
# deployments to the staging environment.
deploy-stg:
  image: $AUTOTAG_IMG
  stage: deploy-stg
  only:
  - /^tmo\/.*$/
  except:
  - tags
  services:
  - name: $GITLAB_CORE_IMG
    alias: gitlab-core

  # Note: Again, the design is to have the job set a tag of the form
  # "tmo/rel/NNN", where "NNN" matches the currently set "tmo/rc/NNN"
  # tag for this commit.  (And again, there is also support for using
  # short-lived release branches, which reqire a slightly different
  # naming scheme: "tmo/rel/NNN.MMM".)  The steps are similar to the
  # "deploy-qa" job, but notice the different invocation for autotag.
  script:
  - autotag from
  - echo "Deploy to STG"

  # We use "stg" as the name of the environment to deploy to.
  environment:
    name: stg

  # Again, make this job a manual job, and prohibit deployment to
  # production unless successful deployment to staging has occurred.
  when: manual
  allow_failure: false

# This is the final deployment job: deployment to production.
deploy-prod:
  image: $AUTOTAG_IMG
  stage: deploy-prod
  only:
  - /^tmo\/.*$/
  except:
  - tags
  services:
  - name: $GITLAB_CORE_IMG
    alias: gitlab-core

  script:
  - autotag move tmo/prod
  - echo "Deploy to PROD"

  # We use "prod" as the name of the environment to deploy to.
  environment:
    name: prod

  # This again makes this job a manually-triggered job.
  when: manual
  allow_failure: false
