include:
  - project: 'tmobile/templates'
    ref: chub
    file:
      - /gitlab-ci/.tmo.global.common.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.mavenTest.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.mavenBuild.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.mavenPublish.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.fortify.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.sonar.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.badge.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.ctp-e2egating.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.shellcheck.gitlab-ci.yml
      - /gitlab-ci/.tmo.job.docker.gitlab-ci.yml
     # - /gitlab-ci/.tmo.job.container-scan.gitlab-ci.yml

stages: 
  - tmo
  - build
  - test
  - package
  - publish
  - ci
  - deploy

testjob:
  stage: tmo
  image: alpine
  script:
    - echo $CI_REPOSITORY_URL
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_DEFAULT_BRANCH

variables:
  # Common
  APP_VERSION: "1.0"
  BUILD_NUMBER: "$CI_COMMIT_SHORT_SHA"
  # Maven
  MAVEN_PUBLISH_ARGS: "-Dfile=target/${CI_PROJECT_NAME}-${APP_VERSION}-$CI_COMMIT_SHORT_SHA.jar"
  JACOCO_COVERAGE_REPORT: "yes"
  # Docker
  DOCKER_BUILD_ARGS: "--build-arg APP_VERSION=$APP_VERSION --build-arg PROJECT_NAME=$CI_PROJECT_NAME --build-arg COMMIT_SHA=$CI_COMMIT_SHORT_SHA"
  # Child
  PARENT_PIPELINE_ID: $CI_PIPELINE_ID

  MAVEN_BUILD_SINGLE_JOB: "true"

# Create json for badges 
pages:
  extends: .badge_pages
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"
      when: on_success

.deploy-rules: &deploy-rules
  rules:
   - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH || $DEPLOY_ALL == "true"
     when: on_success
   - when: never

# K8s Deployments
npe-k8s:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/k8s/npe-stg.yaml
    strategy: depend
  <<: *deploy-rules

prod-k8s:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/k8s/prod.yaml
    strategy: depend
  <<: *deploy-rules

# PCF Deployments
npe-pcf:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/pcf/npe.yaml
    strategy: depend
  <<: *deploy-rules

prod-pcf:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/pcf/prod.yaml
    strategy: depend
  <<: *deploy-rules

# PCF Reviews
review-pcf:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/pcf/review.yaml
    strategy: depend
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH #only topic branches
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "trigger" #pushes only
      when: on_success
    - when: never

# K8s Reviews
review-k8s:
  stage: deploy
  trigger:
    include: gitlab-ci/deploy/helloworld/k8s/review.yaml
    strategy: depend
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH # only topic branches
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "trigger" # pushes only
      when: on_success
    - when: never
