##################################### px-cde02 ################################################

.vars_px-cde02_prod:
    variables:
      PCF_API: "api.sys.px-cde02.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-cde02.cf.t-mobile.com"

##################################### px-cde11a ################################################

.vars_px-cde11a_prod:
    variables:
      PCF_API: "api.sys.px-cde11a.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-cde11a.cf.t-mobile.com"

##################################### px-cde03a ################################################

.vars_px-cde03a_prod:
    variables:
      PCF_API: "api.sys.px-cde03a.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-cde03a.cf.t-mobile.com"

##################################### tt-cde02a ################################################

.vars_tt-cde02a_prod:
    variables:
      PCF_API: "api.sys.tt-cde02a.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.tt-cde02a.cf.t-mobile.com"
