##################################### px-npe02a ################################################

.vars_px-npe02a_dev:
    variables:
      PCF_API: "api.sys.px-npe02a.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe02a.cf.t-mobile.com"

.vars_px-npe02a_stg:
    variables:
      PCF_API: "api.sys.px-npe02a.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe02a.cf.t-mobile.com"

##################################### px-npe02b ################################################

.vars_px-npe02b_dev:
    variables:
      PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe02b.cf.t-mobile.com"

.vars_px-npe02b_stg:
    variables:
      PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe02b.cf.t-mobile.com"

##################################### px-npe02c ################################################

.vars_px-npe02c_dev:
    variables:
      PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe02c.cf.t-mobile.com"

.vars_px-npe02c_stg:
    variables:
      PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe02c.cf.t-mobile.com"

##################################### px-npe03a ################################################
.vars_px-npe03a_dev:
    variables:
      PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe03a.cf.t-mobile.com"

.vars_px-npe03a_stg:
    variables:
      PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe03a.cf.t-mobile.com"

##################################### px-npe03b ################################################
.vars_px-npe03b_dev:
    variables:
      PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe03b.cf.t-mobile.com"


.vars_px-npe03b_stg:
    variables:
      PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe03b.cf.t-mobile.com"

##################################### px-npe03d ################################################

.vars_px-npe03d_dev:
    variables:
      PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
      PCF_SPACE: "development"
      DOMAIN: "dev.px-npe03d.cf.t-mobile.com"

.vars_px-npe03d_stg:
    variables:
      PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
      PCF_SPACE: "staging"
      DOMAIN: "test.px-npe03d.cf.t-mobile.com"
