#!/bin/bash

# find_latest <commit> <pfx> <sfx>
#
# Finds the latest version from a tag matching the specified prefix
# and suffix and reachable from the specified commit.  Standard output
# will be that latest version string.
find_latest () {
    local commit=$1
    local pfx=$2
    local sfx=$3
    local -a tags pfx_stripped versions

    # First, load the tags
    mapfile -t tags < <(git tag --merged ${commit} ${pfx}*${sfx})

    # Strip the tag prefixes and suffixes
    pfx_stripped=("${tags[@]##${pfx}}")
    versions=("${pfx_stripped[@]%%${sfx}}")

    # Sort the versions and extract the latest
    echo "${versions[@]}" | sed 's/ /\n/g' | sort -r -V | head -1
}

# increment <version> <comps> [<which> [<incr>]]
#
# Increments the version at the specified <which> (defaults to -1) by
# the specified <incr> (defaults to 1).  The <comps> value specifies
# the expected number of components of the version number.  Standard
# output will be the incremented version.  Fails if <which> is outside
# the range [-n, n), where n is the maximum of the number of
# components in version and the value of <comps>.  (In range notation,
# square brackets ('[' and ']') indicate that the range includes that
# number, while round brackets (parentheses, '(' and ')') indicate
# that the range excludes that number.)
increment () {
    # First, split the version on .
    local oIFS="${IFS}"
    IFS="${IFS}."
    local -a version=($1)
    IFS="${oIFS}"

    # Next, how many components do we expect?
    local comps=$2

    # Which component to increment?
    local whichcomp=${3--1}

    # And the size of the increment
    local incr=${4-1}

    # Extend the version as needed
    local i
    for (( i=${#version[@]}; ${i} < ${comps}; i++ )); do
         version[${i}]=0
    done

    # Normalize whichcomp
    if [[ ${whichcomp} -lt 0 ]]; then
        whichcomp=$((${whichcomp} + ${#version[@]}))
    fi
    if [[ ${whichcomp} -lt 0 || ${whichcomp} -ge ${#version[@]} ]]; then
        echo "Index ${whichcomp} out of range" >&2
        return 1
    fi

    # Apply the increment
    version[${whichcomp}]=$((${version[${whichcomp}]} + ${incr}))

    # Zero remaining elements
    for (( i=${whichcomp} + 1; ${i} < ${#version[@]}; i++ )); do
        version[${i}]=0
    done

    echo "${version[@]}" | sed 's/ /./g'
}

# tag_exists <tag>
#
# Checks to see if the specified tag exists in the current git
# repository.  Tests as true if it does, false otherwise.
tag_exists () {
    git rev-parse -q --verify "$1" >/dev/null
}

# tag_create <tag> <commit>
#
# Creates the specified tag, pointing to the specified commit.
tag_create () {
    local tag=$1
    local commit=$2

    # Stubbed; for now, just echos what it would do
    echo "Here would create tag ${tag} pointing to ${commit}"
}

# tag_move <tag> <commit>
#
# Moves an already existing tag, making it now point to the specified
# commit.
tag_move () {
    local tag=$1
    local commit=$2

    # Stubbed; for now, just echos what it would do
    echo "Here would move tag ${tag} to point to ${commit}"
}

# get_commit [<commit>]
#
# Gets a commit ID.  Prefers the passed-in value, then the
# CI_COMMIT_SHA value, then the SHA of the current HEAD.
get_commit () {
    local commit=$1

    # If it's passed on the command line, just return it
    if [[ "${commit}" != "" ]]; then
        echo "${commit}"
        return 0
    fi

    # Is it available from the gitlab environment?
    if [[ "${CI_COMMIT_SHA}" != "" ]]; then
        echo "${CI_COMMIT_SHA}"
        return 0
    fi

    # Get it from the repository
    git rev-parse HEAD
}

# get_branch [<branch>]
#
# Gets a branch name.  Prefers the passed-in value, then the
# CI_COMMIT_REF_NAME value, then what git reports for --abbrev-ref of
# HEAD.
get_branch () {
    local branch=$1

    # If it's passed on the command line, just return it
    if [[ "${branch}" != "" ]]; then
        echo "${branch}"
        return 0
    fi

    # Is it available from the gitlab environment?
    if [[ "${CI_COMMIT_REF_NAME}" != "" ]]; then
        echo "${CI_COMMIT_REF_NAME}"
        return 0
    fi

    # Get it from the repository
    git rev-parse --abbrev-ref HEAD
}

# Rules for evaluating branch names to retrieve counts.
branch_rules=(${BRANCH_RULES:-tmo/master:1 tmo/*:2})

# get_count <branch>
#
# Retrieve the count corresponding to the branch name.
get_count () {
    local branch=$(get_branch "$1")
    local i trial

    # Go through the rules one by one
    for (( i=0; i < ${#branch_rules[@]}; i++ )); do
        trial=$(echo "${branch_rules[${i}]}" | sed 's/:.*//')
        if [[ "${branch}" == ${trial} ]]; then
            echo "${branch_rules[${i}]}" | sed 's/^[^:]*://'
            return 0
        fi
    done
}

# arg_set <name> <value>
#
# Sets the variable with the given <name> to <value>.  Can be used as
# an action with arg_parse.
arg_set () {
    local -n name=$1
    name=$2
}

# arg_push <name> <value>
#
# Adds <value> to an array with the given <name>.  Can be used as an
# action with arg_parse.
arg_push () {
    local -n name=$1
    name[${#name[@]}]=$2
}

# arg_clear <name>
#
# Clears an argument.  Can be used as an action with arg_parse.
arg_clear () {
    local name=$1
    unset ${name}
}

# arg_error <code> <message>
#
# Emits an error message to the standard error output.  Can be used as
# an action with arg_parse.  Returns the specified error code.
arg_error () {
    local code=$1
    shift

    # Emit the message
    echo "$@" >&2

    return ${code}
}

# _arg_wrap <width> <l1indent> <indent> <text>
#
# Word-wraps the given <text> to the specified <width>, which also
# accounts for a line one indent <l1indent> and subsequent <indent>.
# This is used by the arg_usage routine to output pretty help text.
_arg_wrap () {
    local width=$1
    local l1indent=$2
    local indent=$3
    local text=$4

    awk -v WIDTH=${width} -v L1INDENT="${l1indent}" \
        -v INDENT="${indent}" -v TEXT="${text}" \
'
function wrap(text,   i, linelen, result) {
    linelen = length(L1INDENT)
    while (text) {
        i = match(text, / |$/)
        linelen += i
        if (linelen > WIDTH) {
            result = result RS INDENT
            linelen = i - 1 + length(INDENT)
        } else if (result) {
            result = result FS
        } else {
            result = L1INDENT
        }
        result = result substr(text, 1, i - 1)
        text = substr(text, i + 1)
    }
    return result
}

END {
    print wrap(TEXT)
}
' /dev/null
}

# arg_usage <code> <pfx> <desc> <argdesc> [<argdesc> [...]] [-- <command>]
#
# This is a very complex shell function that generates and outputs a
# usage message for commands, in conjunction with arg_parse.  If
# <code> is 0, the message will be sent to standard output; otherwise,
# it's sent to standard error.  In either case, the application exits
# with the specified exit code.  At the end of processing, if an
# additional <command> was specified, it will be called and its
# standard output redirected to the correct place; the last argument
# will be the appropriate screen width.
#
# See arg_parse for details on the structure of <argdesc>.
arg_usage () {
    local usage_code=$1 usage_pfx=$2 usage_desc=$3
    shift 3
    local -a usage_opts
    local -a usage_args
    local -a usage_other
    local -a tmp
    local width=72
    local state=setup metastate=present
    local oIFS=${IFS}
    local depth=0 args=0
    local i leadin text meta first
    local textindent='                '

    # Begin by opening fd 3 to the appropriate output
    if [[ ${usage_code} -eq 0 ]]; then
        exec 3>&1
    else
        exec 3>&2
    fi

    # Compose the preamble
    local preamble="Usage: $(basename $0)"
    if [[ "${usage_pfx}" != "" ]]; then
        preamble="${preamble} ${usage_pfx}"
    fi
    local pre_indent=$(awk -v LEN=$((${#preamble} + 1)) 'END {printf "%*s", LEN, ""}' /dev/null)
    preamble="${preamble} [<options>]"

    # Separate the option and argument descriptions
    while [[ $# -gt 0 ]]; do
        if [[ ${state} == "setup" ]]; then
            # Are we done?
            if [[ "$1" == "--" ]]; then
                # Switch state to other
                state=other

                # Close the preamble
                if [[ ${metastate} == "present" && ${args} == ${#usage_args[@]} ]]; then
                    preamble="${preamble} [...]"
                fi
                while [[ ${depth} -gt 0 ]]; do
                    preamble="${preamble}]"
                    depth=$((${depth} - 1))
                done

                # Must skip "--" or we'll misunderstand it
                shift

                continue
            fi

            # Split the argument description
            IFS="|"
            tmp=($1)
            IFS=${oIFS}

            # Is it positional or an option?
            if [[ "${tmp[0]}" == "" && "${tmp[1]}" == "" ]]; then
                usage_args[${#usage_args[@]}]=$1

                # Add argument to the preamble
                if [[ "${tmp[5]}" == "" ]]; then
                    metastate=absent
                elif [[ ${metastate} == "absent" ]]; then
                    echo "Positional argument with meta present after positional argument with absent meta" >&2
                    exit 128
                elif [[ "${tmp[2]}" == "" || "${tmp[2]}" -eq 0 ]]; then
                    preamble="${preamble} [<${tmp[5]}>"
                    depth=$(($depth + 1))
                else
                    preamble="${preamble} <${tmp[5]}>"
                fi

                args=$(($args + 1))
            else
                usage_opts[${#usage_opts[@]}]=$1
            fi
        else
            usage_other[${#usage_other[@]}]=$1
        fi

        shift
    done

    # Clean up the preamble
    if [[ ${state} == "setup" ]]; then
        # Close the preamble
        if [[ ${metastate} == "present" && ${args} == ${#usage_args[@]} ]]; then
            preamble="${preamble} [...]"
        fi
        while [[ ${depth} -gt 0 ]]; do
            preamble="${preamble}]"
            depth=$((${depth} - 1))
        done
    fi

    # Emit the preamble
    _arg_wrap ${width} '' "${pre_indent}" "${preamble}" >&3
    echo >&3

    # Output the description
    _arg_wrap ${width} '' '' "${usage_desc}" >&3

    # Document the arguments
    if [[ ${#usage_args[@]} -gt 0 ]]; then
        echo >&3
        echo "ARGUMENTS:" >&3
        first=true

        for ((i=0; i < ${#usage_args[@]}; i++)); do
            # Emit a blank line if needed
            if [[ ${first} == false ]]; then
                echo >&3
            else
                first=false
            fi

            # Split the argument description again
            IFS="|"
            tmp=(${usage_args[${i}]})
            IFS=${oIFS}

            # If it doesn't have a meta, we're done
            if [[ "${tmp[5]}" == "" ]]; then
                break
            fi

            # Set the lead-in
            leadin="  <${tmp[5]}>"

            # Get the help text
            if [[ "${tmp[6]}" == "" ]]; then
                text="No help available."
            else
                text=${tmp[6]}
            fi

            # Can leadin be combined with the help text?
            if [[ ${#leadin} -lt 14 ]]; then
                while [[ ${#leadin} -lt 16 ]]; do
                    leadin="${leadin} "
                done
                _arg_wrap ${width} "${leadin}" "${textindent}" "${text}" >&3
            else
                echo "${leadin}" >&3
                _arg_wrap ${width} "${textindent}" "${textindent}" "${text}" >&3
            fi
        done
    fi

    # Now hit the options
    if [[ ${#usage_opts[@]} -gt 0 ]]; then
        echo >&3
        echo "OPTIONS:" >&3
        first=true

        for ((i=0; i < ${#usage_opts[@]}; i++)); do
            # Emit a blank line if needed
            if [[ ${first} == false ]]; then
                echo >&3
            else
                first=false
            fi

            # Split the option description again
            IFS="|"
            tmp=(${usage_opts[${i}]})
            IFS=${oIFS}

            # Does it take arguments?
            meta=
            if [[ "${tmp[2]}" != "" && "${tmp[2]}" -gt 0 ]]; then
                if [[ "${tmp[5]}" != "" ]]; then
                    meta="<${tmp[5]}>"
                elif [[ "${tmp[0]}" != "" ]]; then
                    meta="<${tmp[0]}>"
                else
                    echo "Option -${tmp[1]} has no meta" >&2
                    exit 128
                fi
            fi

            # Start with the long option, if any
            if [[ "${tmp[0]}" != "" ]]; then
                leadin="  --${tmp[0]}"
                if [[ "${meta}" != "" ]]; then
                    leadin="${leadin}=${meta}"
                fi
            fi

            # Now hit the short option, if any
            if [[ "${tmp[1]}" != "" ]]; then
                if [[ "${leadin}" != "" ]]; then
                    echo "${leadin}" >&3
                fi
                leadin="  -${tmp[1]}"
                if [[ "${meta}" != "" ]]; then
                    leadin="${leadin} ${meta}"
                fi
            fi

            # Get the help text
            if [[ "${tmp[6]}" == "" ]]; then
                text="No help available."
            else
                text=${tmp[6]}
            fi

            # Can leadin be combined with the help text?
            if [[ ${#leadin} -lt 14 ]]; then
                while [[ ${#leadin} -lt 16 ]]; do
                    leadin="${leadin} "
                done
                _arg_wrap ${width} "${leadin}" "${textindent}" "${text}" >&3
            else
                echo "${leadin}" >&3
                _arg_wrap ${width} "${textindent}" "${textindent}" "${text}" >&3
            fi
        done
    fi

    # Invoke others
    if [[ ${#usage_other[@]} -gt 0 ]]; then
        eval "${usage_other[@]}" ${width} >&3
    fi

    # Close the stream
    exec 3>&-

    # Exit with the code
    exit ${usage_code}
}

# _arg_optname <value>
#
# Extracts the option name <opt> from a string of the form
# "--<opt>=<val>".  Used by arg_parse.
_arg_optname () {
    echo "$@" | sed -e 's/=.*$//' -e 's/^--//'
}

# _arg_optval <value>
#
# Extracts the option value <val> from a string of the form
# "--<opt>=<val>".  Used by arg_parse.
_arg_optval () {
    echo "$@" | sed 's/^[^=]*=//'
}

# arg_parse <pfx> <desc> <argdesc> [<argdesc> [...]] -- <arg> [<arg> [...]]
#
# This is a very complex shell function that implements option
# parsing.  While the function does not include support for generating
# help text, it does collect the information that a usage routine may
# rely on.
#
# Arguments are defined by passing one or more '|'-separated strings,
# followed by a "--" argument; what follows "--" is assumed to be the
# actual arguments to process.  The fields in the argument definitions
# are as follows:
#
# +----------------------+--------------------------------------------+
# | Name                 | Description                                |
# +======================+============================================+
# | Long name            | Long option name, e.g., "foo" for "--foo". |
# +----------------------+--------------------------------------------+
# | Short name           | Short option name, e.g., "f" for "-f".     |
# +----------------------+--------------------------------------------+
# | Value/required flag  | Integer flag; indicates value required for |
# |                      | options, argument required for positional  |
# |                      | arguments.                                 |
# +----------------------+--------------------------------------------+
# | Action               | The action to perform.  Passed the value   |
# |                      | (if any) as the last parameter.  Invoked   |
# |                      | using eval.                                |
# +----------------------+--------------------------------------------+
# | Stop processing flag | Indicates option processing should be      |
# |                      | stopped if "true".  Defaults to "false".   |
# +----------------------+--------------------------------------------+
# | Meta variable        | Used to describe the option value or the   |
# |                      | argument in error messages and help text.  |
# +----------------------+--------------------------------------------+
# | Help text            | Help text for the option or argument.      |
# +----------------------+--------------------------------------------+
#
# To declare a positional argument, omit the long and short names.
# With the exception of the "action" field, all fields have reasonable
# defaults, with the "meta" defaulting to the long option name if set.
# The last declared positional argument "telescopes", meaning its
# action is used for all remaining positional arguments; you may want
# to use the act_error action to refuse additional positional
# arguments.  Finally, the required flag on positional arguments must
# not be non-zero after the first positional argument that sets it to
# 0; e.g., all required positional arguments must occur at the
# beginning of the set of positional arguments.
#
# When an error occurs during argument processing, arg_parse will emit
# an error message to standard error and exit with an appropriate
# code, usually "1" for errors detected within the body of arg_parse
# and whatever return code the action returned with for those sorts of
# errors.  If errors are detected while processing the argument
# _descriptions_, this indicates a programming error, and the return
# code will be "128", with the error message indicating the index of
# the bad argument description.
#
# The variables "usage_pfx" and "usage_desc" contain the first two
# arguments passed to arg_parse, and the array variable "usage_opts"
# contains the option descriptions and positional argument
# descriptions; these values may be referenced from the action,
# allowing operation of a "usage" routine with this information.
arg_parse () {
    local usage_pfx=$1 usage_desc=$2
    shift 2
    local -A arg_long
    local -A arg_short
    local -a arg_count
    local -a arg_action
    local -a arg_pos
    local -a arg_stop
    local -a arg_meta
    local -a usage_opts
    local -a usage_args
    local -a tmp
    local state=setup req=true
    local oIFS=${IFS}
    local pos=0 roll=false
    local has_help=false has_h=false
    local idx opt val i stop meta

    while [[ $# -gt 0 ]]; do
        if [[ ${state} == "setup" ]]; then
            # Are we done?
            if [[ "$1" == "--" ]]; then
                # Make sure there's an action for positional arguments
                if [[ ${#arg_pos[@]} -eq 0 ]]; then
                    arg_pos[0]="arg_error 1 No positional arguments accepted"
                fi

                # Add a help action
                if [[ ${has_help} == false || ${has_h} == false ]]; then
                    idx=${#arg_count[@]}
                    arg_count[${idx}]=0
                    arg_action[${idx}]='arg_usage 0 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"'
                    arg_stop[${idx}]=false

                    if [[ ${has_help} == false ]]; then
                        arg_long[help]=${idx}
                        val='help|'
                    else
                        val='|'
                    fi
                    if [[ ${has_h} == false ]]; then
                        arg_short[h]=${idx}
                        val="${val}h|"
                    else
                        val="${val}|"
                    fi
                    usage_opts[${#usage_opts[@]}]="${val}"'0||||Emit this help message'
                fi

                # Switch state to parse
                state=parse

                # Must skip "--" or we'll misunderstand it
                shift

                continue
            fi

            # Save the option specification
            usage_opts[${#usage_opts[@]}]=$1

            # Use an index to identify what to do with it
            idx=${#arg_count[@]}

            # Split the argument description
            IFS="|"
            tmp=($1)
            IFS=${oIFS}

            # Process the argument description
            if [[ "${tmp[0]}" != "" ]]; then
                # Save the long option name
                arg_long[${tmp[0]}]=${idx}
                arg_meta[${idx}]=${tmp[0]}

                # Is it help?
                if [[ ${tmp[0]} == "help" ]]; then
                    has_help=true
                fi
            fi
            if [[ "${tmp[1]}" != "" ]]; then
                # Save the short option name
                arg_short[${tmp[1]}]=${idx}

                # Is it h?
                if [[ ${tmp[1]} == "h" ]]; then
                    has_h=true
                fi
            fi
            if [[ "${tmp[2]}" != "" ]]; then
                # Number of arguments consumed
                arg_count[${idx}]=${tmp[2]}
            else
                # No arguments consumed
                arg_count[${idx}]=0
            fi
            if [[ "${tmp[0]}" == "" && "${tmp[1]}" == "" ]]; then
                # Save the positional argument name
                arg_pos[${#arg_pos[@]}]=${idx}
                if [[ "${req}" == "true" && ${arg_count[${idx}]} -eq 0 ]]; then
                    req=false
                elif [[ "${req}" == "false" && ${arg_count[${idx}]} -gt 0 ]]; then
                    echo "Required positional argument after optional positional argument at index ${idx}" >&2
                    exit 128
                fi
            fi
            if [[ "${tmp[3]}" != "" ]]; then
                # Save the action
                arg_action[${idx}]=${tmp[3]}
            else
                # No action provided
                echo "Action at index ${idx} missing" >&2
                exit 128
            fi
            if [[ "${tmp[4]}" != "" ]]; then
                # Argument processing should stop
                arg_stop[${idx}]=${tmp[4]}
            else
                arg_stop[${idx}]=false
            fi
            if [[ "${tmp[5]}" != "" ]]; then
                # Argument meta is provided
                arg_meta[${idx}]=${tmp[5]}
            fi
        elif [[ ${state} == "parse" ]]; then
            stop=unknown
            idx=

            case "$1" in
                --)
                    stop=true
                    state=posonly
                    ;;
                --*=*)
                    opt=$(_arg_optname "$1")
                    val=$(_arg_optval "$1")

                    # Begin by looking up the index
                    idx=${arg_long[${opt}]}
                    if [[ "${idx}" == "" ]]; then
                        echo "Unknown option \"--${opt}\"" >&2
                        arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                    fi

                    # Make sure it takes an argument
                    if [[ "${arg_count[${idx}]}" -lt 1 ]]; then
                        echo "Option \"--${opt}\" does not take an argument" >&2
                        arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                    fi

                    # Invoke the action
                    if eval "${arg_action[${idx}]} '${val}'"; then
                        :
                    else
                        exit $?
                    fi
                    ;;
                --*)
                    opt=$(_arg_optname "$1")

                    # Begin by looking up the index
                    idx=${arg_long[${opt}]}
                    if [[ "${idx}" == "" ]]; then
                        echo "Unknown option \"--${opt}\"" >&2
                        arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                    fi

                    # Does it take an argument?
                    if [[ "${arg_count[${idx}]}" -eq 0 ]]; then
                        # Just invoke the action
                        if eval "${arg_action[${idx}]}"; then
                            :
                        else
                            exit $?
                        fi
                    else
                        if [[ $# -lt 2 ]]; then
                            echo "Option \"--${opt}\" takes an argument" >&2
                            arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                        fi

                        # Get the option and invoke the action
                        shift
                        if eval "${arg_action[${idx}]} '$1'"; then
                            :
                        else
                            exit $?
                        fi
                    fi
                    ;;
                -*)
                    for ((i=1; i < ${#1}; i++)); do
                        opt=${1:${i}:1}

                        # Begin by looking up the index
                        idx=${arg_short[${opt}]}
                        if [[ "${idx}" == "" ]]; then
                            echo "Unknown option \"-${opt}\"" >&2
                            arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                        fi

                        # Does it take an argument?
                        if [[ "${arg_count[${idx}]}" -eq 0 ]]; then
                            # Just invoke the action
                            if eval "${arg_action[${idx}]}"; then
                                :
                            else
                                exit $?
                            fi
                        else
                            # Is there more here?
                            if [[ $((${i} + 1)) -lt ${#1} ]]; then
                                val=${1:$((${i} + 1))}
                            elif [[ $# -lt 2 ]]; then
                                echo "Option \"-${opt}\" takes an argument" >&2
                                arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
                            else
                                shift
                                val=$1
                            fi

                            # Invoke the action
                            if eval "${arg_action[${idx}]} '${val}'"; then
                                :
                            else
                                exit $?
                            fi

                            # Can exit the inner loop
                            break
                        fi
                    done
                    ;;
                *)
                    # Start by looking up the index and incrementing
                    # the pos
                    idx=${arg_pos[${pos}]}
                    pos=$((${pos} + 1))

                    # Invoke the action
                    if eval "${arg_action[${idx}]} '$1'"; then
                        :
                    else
                        exit $?
                    fi
                    ;;
            esac

            # Handle the request to stop argument processing
            if [[ ${stop} == "unknown" && "${idx}" != "" ]]; then
                stop=${arg_stop[${idx}]}
            fi
            if [[ ${stop} == "true" ]]; then
                state=posonly
            fi
        else
            # Start by looking up the index and incrementing the pos
            idx=${arg_pos[${pos}]}
            pos=$((${pos} + 1))

            # Invoke the action
            if eval "${arg_action[${idx}]} '$1'"; then
                :
            else
                exit $?
            fi
        fi

        # Telescope the last positional argument
        if [[ ${state} != "setup" && ${pos} -ge ${#arg_pos[@]} ]]; then
            pos=$((${#arg_pos[@]} - 1))
            roll=true
        fi

        # Done with this argument
        shift
    done

    # Make sure we got the required arguments
    if [[ ${roll} == false ]]; then
        idx=${arg_pos[${pos}]}
        if [[ ${arg_count[${idx}]} -gt 0 ]]; then
            meta=
            if [[ "${arg_meta[${idx}]}" != "" ]]; then
                meta=" <${arg_meta[${idx}]}>"
            fi
            echo "Missing required argument${meta}" >&2
            arg_usage 1 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}"
        fi
    fi
}

# Variables controlling command output.  The dry_run variable keeps
# the command from actually being invoked, while either dry_run or
# verbose set to true will echo the command being invoked.
dry_run=false
verbose=false

# try_run <args>
#
# Conditionally echos and invokes a command specified by <args>.  If
# dry_run is true, the command will not be run.
try_run () {
    if [[ ${dry_run} == "true" || ${verbose} == "true" ]]; then
        echo "$@"
    fi

    if [[ ${dry_run} != "true" ]]; then
        eval "$@"
    fi
}

# The cmds variable contains descriptions of the available
# subcommands, indexed by the name of the subcommand.
declare -A cmds

# cmd_move <args>
#
# Implements the "move" subcommand.  This very simple subcommand will
# either create the tag, if it doesn't already exist, or move it to
# point to a new commit ID.
cmds[move]='Move a tag to the current or specified commit.'
cmd_move () {
    # Parse the command arguments
    tag=
    commit=
    params=(
        '||1|arg_set tag||tag|The tag to move.  Required.'
        '||0|arg_set commit||commit|The commit to use.  Defaults to the current commit.'
        '||0|arg_error 1 Unrecognized positional argument:'
    )
    arg_parse '[<global options>] move' "${cmds[move]}" "${params[@]}" -- "$@"

    # Normalize the commit
    commit=$(get_commit "${commit}")

    # Does the tag exist?
    if tag_exists "${tag}"; then
        try_run tag_move "${tag}" "${commit}"
    else
        try_run tag_create "${tag}" "${commit}"
    fi
}

# cmd_incr <args>
#
# Implements the "incr" subcommand.  This looks up the previous tag
# matching the specified prefix and suffix, increments the version
# number as specified, and creates a new tag, generating an error if
# the tag already exists.
cmds[incr]='Increment the version and create a new tag.'
cmd_incr () {
    # Parse the command arguments
    prefix=tmo/rc/
    suffix=
    count=$(get_count)
    which=-1
    incr=1
    commit=
    params=(
        'prefix|p|1|arg_set prefix||prefix|The prefix of the version tag.'
        'suffix|s|1|arg_set suffix||suffix|The suffix of the version tag.'
        'count|c|1|arg_set count||count|The number of places in the version string.'
        'which|w|1|arg_set which||which|Which place of the version to increment.'
        'incr|i|1|arg_set incr||incr|The amount by which to increment.'
        '||0|arg_set commit||commit|The commit to set the tag to.'
        '||0|arg_error 1 Unrecognized positional argument:'
    )
    arg_parse '[<global options>] incr' "${cmds[incr]}" "${params[@]}" -- "$@"

    # Make sure we have a count
    if [[ "${count}" == "" || "${count}" -lt 1 ]]; then
        echo "Invalid version component count \"${count}\"" >&2
        exit 1
    fi

    # Normalize the commit
    commit=$(get_commit ${commit})

    # Look up the latest version
    version=$(find_latest "${commit}" "${prefix}" "${suffix}")

    # Increment it
    version=$(increment "${version}" "${count}" "${which}" "${incr}")

    # Construct the tag name
    tag="${prefix}${version}${suffix}"

    # If the tag exists, it's an error
    if tag_exists "${tag}"; then
        echo "New tag \"${tag}\" already exists" >&2
        exit 1
    fi

    # Create the tag
    try_run tag_create "${tag}" "${commit}"
}

# cmd_from <args>
#
# Implements the "from" subcommand.  This looks up the latest version
# tag matching a specified prefix and suffix, then constructs and
# creates a new tag using a different prefix and suffix, generating an
# error if the tag already exists.
cmds[from]='Create a new tag with the same version as another tag.'
cmd_from () {
    # Parse the command arguments
    from_prefix=tmo/rc/
    from_suffix=
    prefix=tmo/rel/
    suffix=
    params=(
        'prefix|p|1|arg_set prefix||prefix|The prefix of the tag to create.'
        'suffix|s|1|arg_set suffix||suffix|The suffix of the tag to create.'
        'from-prefix|P|1|arg_set from_prefix||from_prefix|The prefix of the other tag.'
        'from-suffix|S|1|arg_set from_suffix||from_suffix|The suffix of the other tag.'
        '||0|arg_set commit||commit|The commit to set the tag to.'
        '||0|arg_error 1 Unrecognized positional argument:'
    )
    arg_parse '[<global options>] from' "${cmds[from]}" "${params[@]}" -- "$@"

    # Normalize the commit
    commit=$(get_commit ${commit})

    # Look up the latest version
    version=$(find_latest "${commit}" "${from_prefix}" "${from_suffix}")

    # If there's no version, complain
    if [[ "${version}" == "" ]]; then
        echo "Tags matching \"${from_prefix}*${from_suffix}\" do not exist." >&2
        exit 1
    fi

    # Construct the new tag name
    tag="${prefix}${version}${suffix}"

    # If the tag exists, it's an error
    if tag_exists "${tag}"; then
        echo "New tag \"${tag}\" already exists" >&2
        exit 1
    fi

    # Create the tag
    try_run tag_create "${tag}" "${commit}"
}

# cmd_help <args>
#
# Implements the "help" subcommand.  This very simple subcommand
# simply calls another specified subcommand with the --help argument,
# to make it emit its help text.
cmds[help]='Emit help about a subcommand.'
cmd_help () {
    # Parse the command arguments
    subcmd=
    params=(
        '||0|arg_set subcmd||subcmd|The command to get help on.'
        '||0|arg_error 1 Unrecognized positional argument:'
    )
    arg_parse '[<global options>] help' "${cmds[help]}" "${params[@]}" -- "$@"

    # If there's a subcommand, invoke it with "--help"
    if [[ "${subcmd}" != "" ]]; then
        if [[ "${cmds[${subcmd}]}" == "" ]]; then
            echo "No such subcommand \"${subcmd}\"" >&2
            exit 1
        fi

        eval "cmd_${subcmd} --help"
        return 0
    fi

    # Invoke the top-level command with --help
    cmd --help
}

# subcommands
#
# Augments the help text with additional output listing the available
# subcommands.
subcommands () {
    local width=$1
    local first=true
    local leadin
    local textindent='            '

    echo
    echo "SUBCOMMANDS:"

    # Build a sorted list of subcommands
    subcmds=$(echo "${!cmds[@]}" | sed 's/ /\n/g' | sort)

    # Emit data about each one
    for subcmd in ${subcmds}; do
        # Emit a blank line if needed
        if [[ ${first} == false ]]; then
            echo
        else
            first=false
        fi

        # Prepare the leadin
        leadin="  ${subcmd}"

        # Can it be combined with the help text?
        if [[ ${#leadin} -lt 10 ]]; then
            while [[ ${#leadin} -lt 12 ]]; do
                leadin="${leadin} "
            done
            _arg_wrap ${width} "${leadin}" "${textindent}" "${cmds[$subcmd]}"
        else
            echo "${leadin}"
            _arg_wrap ${width} "${textindent}" "${textindent}" "${cmds[$subcmd]}"
        fi
    done
}

# cmd <args>
#
# Implements the main command interpreter.  This parses global
# options, then invokes the appropriate subcommand.
desc='Perform a tag action.  This allows creation of version tags and moving of shifting tags.'
cmd () {
    # Parse the command arguments
    subcmd=
    declare -a subargs
    params=(
        'verbose|v|0|arg_set verbose true|||Enable verbose output.'
        'dry-run|n|0|arg_set dry_run true|||Perform a dry run.'
        'clear-branch-rules|B|0|arg_clear branch_rules|||Clear branch rules.'
        'branch-rule|b|1|arg_push branch_rules||branch_rule|Add a branch rule.'
        'help|h|0|arg_usage 0 "${usage_pfx}" "${usage_desc}" "${usage_opts[@]}" -- subcommands|||Emit this help message.'
        '||1|arg_set subcmd|true|subcmd|The command to perform.'
        '||0|arg_push subargs||args|Options and arguments for the subcommand.'
    )
    arg_parse '' "${desc}" "${params[@]}" -- "$@"

    # Look up the subcommand
    if [[ "${cmds[${subcmd}]}" == "" ]]; then
        echo "No such subcommand \"${subcmd}\"" >&2
        exit 1
    fi

    # Invoke the appropriate subcommand
    eval "cmd_${subcmd} \"\${subargs[@]}\""
}

cmd "$@"
