## Below command will download the tmo-java-base image from tmobile/citadel/containers
FROM registry.gitlab.com/tmobile/citadel/containers/tmo-java-base:{{TMO_JAVA_BASE_IMAGE_VERSION}}

## Variable intake from .gitlab-ci.yml 
ARG APP_VERSION
ARG CI_PROJECT_NAME
ARG CI_COMMIT_SHORT_SHA

## Commands to be executed during the image build
COPY target/$CI_PROJECT_NAME-$APP_VERSION-$CI_COMMIT_SHORT_SHA.jar /run/

RUN ln -s /run/$CI_PROJECT_NAME-$APP_VERSION-$CI_COMMIT_SHORT_SHA.jar /run/app.jar

ENTRYPOINT exec java $JAVA_OPTS -jar /run/app.jar
