endpoints.env.sensitive=false
endpoints.health.sensitive=false
endpoints.refresh.sensitive=false
helloworld.helloworld-2-smoke.url=https://review-helloworld-relic-onboarding.dev.px-npe02a.cf.t-mobile.com/actuator/health
security.basic.enabled=false
