include:
    - local: /.gitlab-ci/common.yaml

# px-prod02
px-prd02:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-prd02.cf.t-mobile.com"
    DOMAIN: "apps.px-prd02.cf.t-mobile.com"
  environment:
    name: prod/px-prd02/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-prd02-sanity:
  extends: .sanity
  needs: ["px-prd02"]
  dependencies: ["px-prd02"]
  environment:
    name: prod/px-prd02/smoke
    action: verify

delete-all-routes-apps-px-prd02:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-prd02
  variables:
    PCF_API: "api.sys.px-prd02.cf.t-mobile.com"
    DOMAIN: "apps.px-prd02.cf.t-mobile.com"
  environment:
    name: prod/px-prd02/smoke
    action: stop

# px-prd04
px-prd04:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-prd04.cf.t-mobile.com"
    DOMAIN: "apps.px-prd04.cf.t-mobile.com"
  environment:
    name: prod/px-prd04/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-prd04-sanity:
  extends: .sanity
  needs: ["px-prd04"]
  dependencies: ["px-prd04"]
  environment:
    name: prod/px-prd04/smoke
    action: verify

delete-all-routes-apps-px-prd04:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-prd04
  variables:
    PCF_API: "api.sys.px-prd04.cf.t-mobile.com"
    DOMAIN: "apps.px-prd04.cf.t-mobile.com"
  environment:
    name: prod/px-prd04/smoke
    action: stop

# px-prd03a
px-prd03a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-prd03a.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03a.cf.t-mobile.com"
  environment:
    name: prod/px-prd03a/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-prd03a-sanity:
  extends: .sanity
  needs: ["px-prd03a"]
  dependencies: ["px-prd03a"]
  environment:
    name: prod/px-prd03a/smoke
    action: verify

delete-all-routes-apps-px-prd03a:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-prd03a
  variables:
    PCF_API: "api.sys.px-prd03a.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03a.cf.t-mobile.com"
  environment:
    name: prod/px-prd03a/smoke
    action: stop

# px-prd03b
px-prd03b:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-prd03b.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03b.cf.t-mobile.com"
  environment:
    name: prod/px-prd03b/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-prd03b-sanity:
  extends: .sanity
  needs: ["px-prd03b"]
  dependencies: ["px-prd03b"]
  environment:
    name: prod/px-prd03b/smoke
    action: verify

delete-all-routes-apps-px-prd03b:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-prd03b
  variables:
    PCF_API: "api.sys.px-prd03b.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03b.cf.t-mobile.com"
  environment:
    name: prod/px-prd03b/smoke
    action: stop

# px-prd03c
px-prd03c:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-prd03c.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03c.cf.t-mobile.com"
  resource_group: $CI_JOB_NAME
  environment:
    name: prod/px-prd03c/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-prd03c-sanity:
  extends: .sanity
  needs: ["px-prd03c"]
  dependencies: ["px-prd03c"]
  environment:
    name: prod/px-prd03c/smoke
    action: verify

delete-all-routes-apps-px-prd03c:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-prd03c
  variables:
    PCF_API: "api.sys.px-prd03c.cf.t-mobile.com"
    DOMAIN: "apps.px-prd03c.cf.t-mobile.com"
  environment:
    name: prod/px-prd03c/smoke
    action: stop

# px-cde02
px-cde02a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-cde02.cf.t-mobile.com"
    DOMAIN: "apps.px-cde02.cf.t-mobile.com"
  environment:
    name: prod/px-cde02/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-cde02a-sanity:
  extends: .sanity
  needs: ["px-cde02a"]
  dependencies: ["px-cde02a"]
  environment:
    name: prod/px-cde02/smoke
    action: verify

delete-all-routes-apps-px-cde02:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-cde02
  variables:
    PCF_DELETE_ALL_ROUTES_APPS: "true"
    PCF_API: "api.sys.px-cde02.cf.t-mobile.com"
    DOMAIN: "apps.px-cde02.cf.t-mobile.com"
  environment:
    name: prod/px-cde02/smoke
    action: stop

# px-cde03a
px-cde03a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-cde03a.cf.t-mobile.com"
    DOMAIN: "apps.px-cde03a.cf.t-mobile.com"
  environment:
    name: prod/px-cde03a/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-cde03a-sanity:
  extends: .sanity
  needs: ["px-cde03a"]
  dependencies: ["px-cde03a"]
  environment:
    name: prod/px-cde03a/smoke
    action: verify

delete-all-routes-apps-px-cde03a:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-cde03a
  variables:
    PCF_API: "api.sys.px-cde03a.cf.t-mobile.com"
    DOMAIN: "apps.px-cde03a.cf.t-mobile.com"
  environment:
    name: prod/px-cde03a/smoke
    action: stop

# px-cde11a
px-cde11a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-cde11a.cf.t-mobile.com"
    DOMAIN: "apps.px-cde11a.cf.t-mobile.com"
  environment:
    name: prod/px-cde11a/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

px-cde11a-sanity:
  extends: .sanity
  needs: ["px-cde11a"]
  dependencies: ["px-cde11a"]
  environment:
    name: prod/px-cde11a/smoke
    action: verify

delete-all-routes-apps-px-cde11a:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-cde11a
  variables:
    PCF_API: "api.sys.px-cde11a.cf.t-mobile.com"
    DOMAIN: "apps.px-cde11a.cf.t-mobile.com"
  environment:
    name: prod/px-cde11a/smoke
    action: stop

# tt-cde02a
tt-cde02a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.tt-cde02a.cf.t-mobile.com"
    DOMAIN: "apps.tt-cde02a.cf.t-mobile.com"
  environment:
    name: prod/tt-cde02a/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: production

tt-cde02a-sanity:
  extends: .sanity
  needs: ["tt-cde02a"]
  dependencies: ["tt-cde02a"]
  environment:
    name: prod/tt-cde02a/smoke
    action: verify

delete-all-routes-apps-tt-cde02a:
  extends: .pcf_all_teardown
  resource_group: stop_all_tt-cde02a
  variables:
    PCF_API: "api.sys.tt-cde02a.cf.t-mobile.com"
    DOMAIN: "apps.tt-cde02a.cf.t-mobile.com"
  environment:
    name: prod/tt-cde02a/smoke
    action: stop
