############
# Database #
############
# This repo uses a local H2 database, which maintains the data on your local
# filesystem. This is used for local development purposes only.
# Learn more about H2 here: http://www.h2database.com/html/main.html
#
# Learn more about Spring JPA so you can connect to external DBs here:
# https://www.baeldung.com/the-persistence-layer-with-spring-and-jpa
spring.datasource.url=jdbc:h2:file:./data/helloworld
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.PhysicalNamingStrategy
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=true

##########
# Server #
##########
# The server.port property tells Springboot what port to listen on.
# There are a slew of other server properties documented here:
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server
server.port=80
sample.var=testvalue

#################
# Feature Flags #
#################
# Unleash is the feature flag management framework used by GitLab
# Learn more about Feature Flags in GitLab here:
# https://docs.gitlab.com/ee/operations/feature_flags.html
unleash.instance.api.url=https://gitlab.com/api/v4/feature_flags/unleash/12679731
unleash.instance.id=PpzzkRXXSs5nokqqsrDc

####################
# Health Endpoints #
####################
# Springboot provides various health endpoints via actuators. The properties
# below enable an overall health endpoint 
# (management.endpoint.health.probes.enabled) as well as liveness and readiness
# endpoints that are used for Kubernetes deployments. Learn more about these,
# and other available endpoints, here: 
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
management.endpoint.health.probes.enabled=true

# The show-components setting allows a more granular view of health,
# rather than just UP/DOWN. For example, it will show whether the app can
# connect to its dependencies (DB, message queues, etc) when using the Spring
# provided libraries. You can view a list of auto-configured health indicators
# here: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.auto-configured-health-indicators
# 
# You can also add your own custom indicators (e.g.: test a downstream API).
# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.writing-custom-health-indicators
management.endpoint.health.show-components=always

# Uncommenting the following line will show details about each component 
# (e.g.: DB type and query used to validate connectivity). While there is not
# any known data leakage with these details, we are opting to keep them off
# by default.
# management.endpoint.health.show-details=always

# The next two lines enable liveness and readiness probes used for Kubernetes
# at /actuator/health/liveness and /actuator/health/readiness, respectively
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

management.info.git.mode=full

management.endpoints.web.exposure.include=info,health

management.endpoints.enabled-by-default=true
