include:
    - local: /gitlab-ci/common.yaml

variables:
  K8S_FOUNDATION: "px-npe1103"
  K8S_DOMAIN: "$K8S_FOUNDATION.pks.t-mobile.com"
  K8S_NS: "edponboarding-npe"
  K8S_API_LOGIN_URL: "pksapi.px-npe1001.pks.t-mobile.com"
  K8S_CLUSTER: "api-$K8S_DOMAIN"
  K8S_SERVER_URL: "https://api-$K8S_DOMAIN:8443"
  HELM_VALUES: "./k8s/values.yaml"
  HELM_APP_NAME: $CI_PROJECT_NAME
  HELM_CHARTS_DIR: "./k8s/"
  HELM_HISTORY_MAX: "3"
  HELM_WAIT: "true"

# Deploy on TKE/PKS K8s cluster
px-npe1103:
  stage: deploy
  extends: .helm_deploy
  environment:
    name: qlab01/$K8S_FOUNDATION/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME

px-npe1103-sanity:
  extends: .sanity
  needs: ["px-npe1103"]
  dependencies: ["px-npe1103"]
  environment:
    name: qlab01/$K8S_FOUNDATION/development/smoke
    action: prepare
