include:
    - local: /gitlab-ci/common.yaml

# px-npe02a
npe02a-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02a.cf.t-mobile.com"
    DOMAIN: "test.px-npe02a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02a/staging/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe02a-stg-sanity:
  extends: .sanity
  needs: ["npe02a-stg"]
  dependencies: ["npe02a-stg"]
  environment:
    name: qlab01/px-npe02a/staging/smoke
    action: prepare

delete-all-routes-apps-px-npe02a:
  extends: .allteardown
  resource_group: stop_all_px-npe02a
  variables:
    PCF_API: "api.sys.px-npe02a.cf.t-mobile.com"
    DOMAIN: "test.px-npe02a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02a/staging/smoke
    action: stop

# px-npe02b-development
npe02b-dev:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
    PCF_SPACE: "development"
    DOMAIN: "dev.px-npe02b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02b/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe02b-dev-sanity:
  extends: .sanity
  needs: ["npe02b-dev"]
  dependencies: ["npe02b-dev"]
  environment:
    name: qlab01/px-npe02b/development/smoke
    action: prepare

delete-all-routes-apps-px-npe02b:
  extends: .allteardown
  resource_group: stop_all_px-npe02b
  variables:
    PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
    PCF_SPACE: "development"
    DOMAIN: "dev.px-npe02b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02b/development/smoke
    action: stop

# px-npe02b-staging  
npe02b-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
    PCF_SPACE: "staging"
    DOMAIN: "test.px-npe02b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02b/staging/smoke 
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe02b-stg-sanity:
  extends: .sanity
  needs: ["npe02b-stg"]
  dependencies: ["npe02b-stg"]
  environment:
    name: qlab01/px-npe02b/staging/smoke
    action: prepare

# px-npe02c development
npe02c-dev:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02c.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02c/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe02c-dev-sanity:
  extends: .sanity
  needs: ["npe02c-dev"]
  dependencies: ["npe02c-dev"]
  environment:
    name: qlab01/px-npe02c/development/smoke
    action: prepare

delete-all-routes-apps-px-npe02c:
  extends: .allteardown
  resource_group: stop_all_px-npe02c
  variables:
    PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02c.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02c/development/smoke
    action: stop
    
# px-npe02c staging 
npe02c-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
    PCF_SPACE: "staging"
    DOMAIN: "test.px-npe02c.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02c/staging/smoke 
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe02c-stg-sanity:
  extends: .sanity
  needs: ["npe02c-stg"]
  dependencies: ["npe02c-stg"]
  environment:
    name: qlab01/px-npe02c/staging/smoke
    action: prepare
  
# px-npe03a development
npe03a-dev:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03a/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development
  
npe03a-dev-sanity:
  extends: .sanity
  needs: ["npe03a-dev"]
  dependencies: ["npe03a-dev"]
  environment:
    name: qlab01/px-npe03a/development/smoke
    action: prepare

delete-all-routes-apps-px-npe03a:
  extends: .allteardown
  resource_group: stop_all_px-npe03a
  variables:
    PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03a/development/smoke
    action: stop 

# px-npe03a staging
npe03a-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
    PCF_SPACE: "staging"
    DOMAIN: "test.px-npe03a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03a/staging/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe03a-stg-sanity:
  extends: .sanity
  needs: ["npe03a-stg"]
  dependencies: ["npe03a-stg"]
  environment:
    name: qlab01/px-npe03a/staging/smoke
    action: prepare

# px-npe03b development
npe03b-dev:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03b/development/smoke
    url: http://${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development

npe03b-dev-sanity:
  extends: .sanity
  needs: ["npe03b-dev"]
  dependencies: ["npe03b-dev"]
  environment:
    name: qlab01/px-npe03b/development/smoke
    action: prepare

delete-all-routes-apps-px-npe03b:
  extends: .allteardown
  resource_group: stop_all_px-npe03b
  variables:
    PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03b/development/smoke
    action: stop
  
# px-npe03b staging 
npe03b-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
    PCF_SPACE: "staging"
    DOMAIN: "test.px-npe03b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03b/staging/smoke 
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe03b-stg-sanity:
  extends: .sanity
  needs: ["npe03b-stg"]
  dependencies: ["npe03b-stg"]
  environment:
    name: qlab01/px-npe03b/staging/smoke
    action: prepare

# px-npe03d development
npe03d-dev:
  extends: 
     - .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03d.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03d/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe03d-dev-sanity:
  extends: .sanity
  needs: ["npe03d-dev"]
  dependencies: ["npe03d-dev"]
  environment:
    name: qlab01/px-npe03d/development/smoke
    action: prepare


delete-all-routes-apps-px-npe03d:
  extends: .allteardown
  resource_group: stop_all_px-npe03d
  variables:
    PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03d.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03d/development/smoke
    action: stop

# px-npe03d staging
npe03d-stg:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
    PCF_SPACE: "staging"
    DOMAIN: "test.px-npe03d.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03d/staging/smoke 
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: staging

npe03d-stg-sanity:
  extends: .sanity
  needs: ["npe03d-stg"]
  dependencies: ["npe03d-stg"]
  environment:
    name: qlab01/px-npe03d/staging/smoke
    action: prepare
