include:
    - local: /gitlab-ci/common.yaml


# px-npe02b-development
npe02b:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02b/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe02b-sanity:
  extends: .sanity
  needs: ["npe02b"]
  dependencies: ["npe02b"]
  environment:
    name: qlab01/px-npe02b/development/smoke
    action: verify

delete-all-routes-apps-px-npe02b:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-npe02b
  variables:
    PCF_API: "api.sys.px-npe02b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02b/development/smoke
    action: stop
    deployment_tier: development

# px-npe02c development
npe02c:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02c.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02c/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe02c-sanity:
  extends: .sanity
  needs: ["npe02c"]
  dependencies: ["npe02c"]
  environment:
    name: qlab01/px-npe02c/development/smoke
    action: verify

delete-all-routes-apps-px-npe02c:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-npe02c
  variables:
    PCF_API: "api.sys.px-npe02c.cf.t-mobile.com"
    DOMAIN: "dev.px-npe02c.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe02c/development/smoke
    action: stop
  
# px-npe03a development
npe03a:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03a/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development
  
npe03a-sanity:
  extends: .sanity
  needs: ["npe03a"]
  dependencies: ["npe03a"]
  environment:
    name: qlab01/px-npe03a/development/smoke
    action: verify

delete-all-routes-apps-px-npe03a:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-npe03a
  variables:
    PCF_API: "api.sys.px-npe03a.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03a.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03a/development/smoke
    action: stop 

# px-npe03b development
npe03b:
  extends: .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03b/development/smoke
    url: http://${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development

npe03b-dev-sanity:
  extends: .sanity
  needs: ["npe03b"]
  dependencies: ["npe03b"]
  environment:
    name: qlab01/px-npe03b/development/smoke
    action: verify

delete-all-routes-apps-px-npe03b:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-npe03b
  variables:
    PCF_API: "api.sys.px-npe03b.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03b.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03b/development/smoke
    action: stop

# px-npe03d development
npe03d:
  extends: 
     - .deploy-pcf
  variables:
    PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03d.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03d/development/smoke
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development

npe03d-sanity:
  extends: .sanity
  needs: ["npe03d"]
  dependencies: ["npe03d"]
  environment:
    name: qlab01/px-npe03d/development/smoke
    action: verify


delete-all-routes-apps-px-npe03d:
  extends: .pcf_all_teardown
  resource_group: stop_all_px-npe03d
  variables:
    PCF_API: "api.sys.px-npe03d.cf.t-mobile.com"
    DOMAIN: "dev.px-npe03d.cf.t-mobile.com"
  environment:
    name: qlab01/px-npe03d/development/smoke
    action: stop

