include:
    - local: /gitlab-ci/common.yaml

variables:
  PCF_ROUTE_HOSTNAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  PCF_APP_NAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  INSTANCE_COUNT: 1
  PCF_FOUNDATION: "px-npe02a"
  DOMAIN: "apps.$PCF_FOUNDATION.cf.t-mobile.com"

testpredeploy:
  extends: .testjob
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare
    deployment_tier: development

# Deploy to review environment
px-npe02a:
  extends: .deploy-pcf-review
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development
    on_stop: stop-px-npe02a
    auto_stop_in: 14 days

testpostdeploy:
  image: alpine
  stage: verify
  script:
    - echo "${DYNAMIC_ENVIRONMENT_URL}"
  needs: 
  dependencies: ["px-npe02a"]
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare
    deployment_tier: development

px-npe02a-sanity:
  extends: .sanity
  needs: ["px-npe02a"]
  dependencies: ["px-npe02a"]
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare #will be changed to "verify" hopefully in future
    deployment_tier: development

stop-px-npe02a:
  extends: .pcf-teardown
  needs:
    - px-npe02a
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: stop
    deployment_tier: development
  rules:
    - when: manual
      allow_failure: true


