include:
    - local: /gitlab-ci/common.yaml

variables:
  PCF_ROUTE_HOSTNAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  PCF_APP_NAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  INSTANCE_COUNT: 1
  PCF_FOUNDATION: "px-npe02a"
  DOMAIN: "apps.$PCF_FOUNDATION.cf.t-mobile.com"

testjob:
  extends: .testjob
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare

# Deploy to review environment
deploy-review-pcf:
  extends: .deploy-pcf-review
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development
    on_stop: stop-review-pcf
    auto_stop_in: 14 days

# Stop review environment
stop-review-pcf:
  image: alpine
  stage: deploy
  script:
    - if ! exists "curl" ; then installPackage "curl"; fi;
    - if ! exists "jq" ; then installPackage "jq"; fi;
    - fetchFromCDP "pcf-install.sh" "pcf-install.sh" && sh pcf-install.sh
    - cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -a "$PCF_API" -o "$PCF_ORG" -s "$PCF_SPACE"
    - cf curl /v3/apps | jq -r '.resources[]|select(.name | contains("'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).name' > apps
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete -f $line
      done < "./apps"
    - cf curl /v3/routes | jq -r '.resources[]|select(.host | contains("'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).host' > hosts
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete-route -f $DOMAIN -n $line
      done < "./hosts"
    - echo "Deleted pcf apps $PCF_STOP_APP_NAME in CI_ENVIRONMENT_NAME - $CI_ENVIRONMENT_NAME"
  needs:
    - deploy-review-pcf
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: stop
    deployment_tier: development
  rules:
    - when: manual
      allow_failure: true
  artifacts:
    paths:
      - apps
      - hosts
