include:
    - local: /gitlab-ci/common.yaml

variables:
  PCF_ROUTE_HOSTNAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  PCF_APP_NAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  INSTANCE_COUNT: 1
  PCF_FOUNDATION: "px-npe02a"
  DOMAIN: "apps.$PCF_FOUNDATION.cf.t-mobile.com"

testpredeploy:
  extends: .testjob
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare

# Deploy to review environment
review-pcf:
  extends: .deploy-pcf-review
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    url: $DYNAMIC_ENVIRONMENT_URL
    deployment_tier: development
    on_stop: stop-review-pcf
    auto_stop_in: 14 days

testpostdeploy:
  image: alpine
  stage: verify
  script:
    - echo "${DYNAMIC_ENVIRONMENT_URL}"
  needs:
    - review-pcf
  dependencies:
    - review-pcf
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: prepare

# Stop review environment
stop-review-pcf:
  extends: .pcf-teardown
  needs:
    - review-pcf
  resource_group: review-deploy-$CI_COMMIT_REF_SLUG
  environment:
    name: review/$PCF_FOUNDATION/$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    action: stop
    deployment_tier: development
  rules:
    - when: manual
      allow_failure: true


