include:
    - local: /gitlab-ci/common.yaml

variables:
  K8S_API_LOGIN_URL: "https://api.conducktor.t-mobile.com/api/v3/login?provider=conducktor"
  K8S_SERVER_URL: "https://west.stg.duck.master.kube.t-mobile.com:6443"
  K8S_CLUSTER: "duck-stg-w2"
  K8S_FOUNDATION: "$K8S_CLUSTER"
  K8S_DOMAIN: "$K8S_FOUNDATION.kube.t-mobile.com"
  K8S_NS: "hld-stg-duck-stg-w2"
  HELM_VALUES: "./k8s-conducktor/values.yaml"
  HELM_APP_NAME: $CI_PROJECT_NAME
  HELM_CHARTS_DIR: "./k8s-conducktor/"
  HELM_HISTORY_MAX: "3"
  HELM_WAIT: "true"
  EXTERNAL_DNS_TARGET: "internal-stg-k8s-duck-ing-int-w2-327646687.us-west-2.elb.amazonaws.com"


# Deploy on Conducktor Namespace (hld-stg-duck-stg-w2)
duck-stg-w2:
  stage: deploy
  extends: .helm_deploy
  environment:
    name: stg/duck-stg-w2
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME

duck-stg-w2-sanity:
  extends: .sanity
  needs: ["duck-stg-w2"]
  dependencies: ["duck-stg-w2"]
  environment:
    name: stg/$K8S_FOUNDATION/staging/smoke
    action: verify

