##################################### px-prd02 ################################################

.vars_px-prd02_prod:
    variables:
      PCF_API: "api.sys.px-prd02.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-prd02.cf.t-mobile.com"

##################################### px-prd04 ################################################

.vars_px-prd04_prod:
    variables:
      PCF_API: "api.sys.px-prd04.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-prd04.cf.t-mobile.com"

##################################### px-prd03a ################################################

.vars_px-prd03a_prod:
    variables:
      PCF_API: "api.sys.px-prd03a.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-prd03a.cf.t-mobile.com"

##################################### px-prd03b ################################################

.vars_px-prd03b_prod:
    variables:
      PCF_API: "api.sys.px-prd03b.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-prd03b.cf.t-mobile.com"

##################################### px-prd03c ################################################

.vars_px-prd03c_prod:
    variables:
      PCF_API: "api.sys.px-prd03c.cf.t-mobile.com"
      PCF_SPACE: "production"
      DOMAIN: "apps.px-prd03c.cf.t-mobile.com"
