########################### Anchor Deploy PX-NPE ##############################################

.deploy-px-npe:
  stage: deploy
  extends: .pcf-deploy
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_REF_NAME == "$CI_DEFAULT_BRANCH"
      when: on_success
    - if: $CI_COMMIT_REF_NAME != "$CI_DEFAULT_BRANCH" && $DEPLOY_ALL == "true"
      when: on_success
    - when: never
  resource_group: $CI_JOB_NAME

# Review apps
.deploy-review:
  stage: deploy
  extends: .pcf-deploy
  variables:
    PCF_ROUTE_HOSTNAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    PCF_APP_NAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH  #only topic branches
      when: never
    - if: $CI_PIPELINE_SOURCE != "push"              #pushes only
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS                    #only pushes w/ open m/rs
      when: on_success
    - when: never
  resource_group: $CI_JOB_NAME
    
##################################### Deploy px-npe02a ################################################
# Deploy to review environment
deploy-review:
  extends:
     - .deploy-review
  environment:
    name: review/px-npe02a/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
    on_stop: stop_review
    auto_stop_in: 14 days

# Stop review environment
stop_review:
  image: alpine
  stage: deploy
  script:
    - if ! exists "curl" ; then installPackage "curl"; fi;
    - if ! exists "jq" ; then installPackage "jq"; fi;
    - curl -Os --noproxy '*' $CDP_SERVICE_URL/static/pcf-install.sh && sh pcf-install.sh
    - cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -a "$PCF_API" -o "$PCF_ORG" -s "$PCF_SPACE"
    - cf curl /v3/apps | jq -r '.resources[]|select(.name | startswith("review-'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).name' > apps
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete -f $line
      done < "./apps"
    - cf curl /v3/routes | jq -r '.resources[]|select(.host | startswith("review-'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).host' > hosts
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete-route -f $DOMAIN -n $line
      done < "./hosts"
    - echo "Deleted pcf apps review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG in CI_ENVIRONMENT_NAME - $CI_ENVIRONMENT_NAME"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: never
    - when: manual
      allow_failure: true
  needs:
    - deploy-review
  environment:
    name: review/px-npe02a/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    action: stop
    deployment_tier: development
  artifacts:
    paths:
      - apps
    
# Deploy to Staging environment   
deploy-npe02a-stg:
  extends: 
     - .deploy-px-npe
  variables:
    PCF_API: "api.sys.px-npe02a.cf.t-mobile.com"
    PCF_SPACE: $CI_ENVIRONMENT_TIER
    DOMAIN: "test.px-npe02a.cf.t-mobile.com"
  environment:
    name: stg01/px-npe02a/staging/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging

##################################### Deploy px-npe02b ################################################
# Deploy to Development environment
deploy-npe02b-dev:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe02b_dev
  environment:
    name: dlab01/px-npe02b/development/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
  
# Deploy to Staging environment   
deploy-npe02b-stg:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe02b_stg
  environment:
    name: stg01/px-npe02b/staging/smoke 
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging

##################################### Deploy px-npe02c ################################################
# Deploy to Development environment
deploy-npe02c-dev:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe02c_dev
  environment:
    name: dlab01/px-npe02c/development/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
  
# Deploy to Staging environment   
deploy-npe02c-stg:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe02c_stg
  environment:
    name: stg01/px-npe02c/staging/smoke 
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging
  
##################################### Deploy px-npe03a ################################################
# Deploy to Development environment
deploy-npe03a-dev:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03a_dev
  environment:
    name: dlab01/px-npe03a/development/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
  
  
# Deploy to Staging environment   
deploy-npe03a-stg:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03a_stg
  environment:
    name: stg01/px-npe03a/staging/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging

##################################### Deploy px-npe03b ################################################
# Deploy to Development environment
deploy-npe03b-dev:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03b_dev
  environment:
    name: dlab01/px-npe03b/development/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
  
# Deploy to Staging environment   
deploy-npe03b-stg:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03b_stg
  environment:
    name: stg01/px-npe03b/staging/smoke 
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging

##################################### Deploy px-npe03d ################################################
# Deploy to Development environment
deploy-npe03d-dev:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03d_dev
  environment:
    name: dlab01/px-npe03d/development/smoke
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
  
# Deploy to Staging environment   
deploy-npe03d-stg:
  extends: 
     - .deploy-px-npe
     - .vars_px-npe03d_stg
  environment:
    name: stg01/px-npe03d/staging/smoke 
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: staging
