endpoints.env.sensitive=false
endpoints.health.sensitive=false
endpoints.refresh.sensitive=false
helloworld.helloworld-2-smoke.url=https://helloworld.apps.px-cde02.cf.t-mobile.com/actuator/health
security.basic.enabled=false