include:
    - local: /.gitlab-ci/common.yaml

variables:
  K8S_NS: "cdp-helloworld-stg"
  K8S_API_LOGIN_URL: "pksapi.$K8S_FOUNDATION.tke.t-mobile.com"
  K8S_CLUSTER: "api-$K8S_FOUNDATION.tke.t-mobile.com"
  K8S_SERVER_URL: "https://api-$K8S_FOUNDATION.tke.t-mobile.com:8443"
  K8S_DEPLOY_STRATEGY: "BLUE_GREEN"
  CANARY_INTERVAL: "50s"

# Deploy on TKE/PKS(Gen4) K8s cluster
tt-stg2103-deploy:
  stage: deploy
  extends: .helm_deploy
  variables:
     FLAGGER_MONITORING: "true"
  environment:
    name: stg/$K8S_FOUNDATION/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME

validate_tt-stg2103-deploy:
  stage: post-deploy
  extends: .validate_app
  needs: ["tt-stg2103-deploy"]
  dependencies: ["tt-stg2103-deploy"]

tt-stg2103-promote:
  stage: promote
  extends: .k8s_promote_app
  variables:
     FLAGGER_MONITORING: "true"
  needs: ["tt-stg2103-deploy","validate_tt-stg2103-deploy"]
  dependencies: ["tt-stg2103-deploy","validate_tt-stg2103-deploy"]
  environment:
    name: stg/$K8S_FOUNDATION/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

tt-stg2103-sanity:
  extends: .sanity
  needs: ["tt-stg2103-deploy","tt-stg2103-promote"]
  dependencies: ["tt-stg2103-deploy","tt-stg2103-promote"]
  environment:
    name: stg/$K8S_FOUNDATION/smoke-$HELM_APP_NAME
    action: verify
  retry: 1
  when: delayed
  start_in: 90 seconds

validate_tt-stg2103-promote:
  variables:
    VALIDATE_PHASE: "PROMOTION"
  stage: verify
  extends: .validate_app
  needs: ["tt-stg2103-deploy","tt-stg2103-promote"]
  dependencies: ["tt-stg2103-deploy","tt-stg2103-promote"]

tt-stg2103-rollback:
  stage: rollback
  extends: .helm_rollback
  variables:
     FLAGGER_MONITORING: "true"
  environment:
    name: stg/$K8S_FOUNDATION/smoke-$HELM_APP_NAME
    url: $DYNAMIC_ENVIRONMENT_URL/login
    deployment_tier: staging
  resource_group: $CI_JOB_NAME-$HELM_APP_NAME
  needs: ["validate_tt-stg2103-promote"]
  rules:
    - if: $PARENT_PIPELINE_SOURCE != "schedule"
      when: manual
      allow_failure: true
    - when: on_success

validate_tt-stg2103-rollback:
  variables:
    VALIDATE_PHASE: "ROLLBACK"
  stage: verify-rollback
  extends: .validate_app
  needs: ["tt-stg2103-rollback"]