include:
    - local: /gitlab-ci/common.yaml

variables:
  PCF_ROUTE_HOSTNAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  PCF_APP_NAME: review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
  INSTANCE_COUNT: 1

# Deploy to review environment
deploy-review-pcf:
  extends: .deploy-pcf-review
  environment:
    name: review/px-npe02a/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    url: ${PCF_ROUTE_HOSTNAME}.${DOMAIN}
    deployment_tier: development
    on_stop: stop-review-pcf
    auto_stop_in: 14 days

# Stop review environment
stop-review-pcf:
  image: alpine
  stage: deploy
  script:
    - if ! exists "curl" ; then installPackage "curl"; fi;
    - if ! exists "jq" ; then installPackage "jq"; fi;
    - curl -Os --noproxy '*' $CDP_SERVICE_URL/static/pcf-install.sh && sh pcf-install.sh
    - cf login -u "$CF_USERNAME" -p "$CF_PASSWORD" -a "$PCF_API" -o "$PCF_ORG" -s "$PCF_SPACE"
    - cf curl /v3/apps | jq -r '.resources[]|select(.name | startswith("review-'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).name' > apps
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete -f $line
      done < "./apps"
    - cf curl /v3/routes | jq -r '.resources[]|select(.host | startswith("review-'$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG'")).host' > hosts
    - |
      while IFS= read -r line
      do
        tmoLog "Deleting $line"
        cf delete-route -f $DOMAIN -n $line
      done < "./hosts"
    - echo "Deleted pcf apps review-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG in CI_ENVIRONMENT_NAME - $CI_ENVIRONMENT_NAME"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH #only topic branches
      when: never
    - if: $CI_PIPELINE_SOURCE != "push"             #pushes only
      when: never
    - if: $CI_OPEN_MERGE_REQUESTS                   #only pushes w/ open m/rs
      when: manual
      allow_failure: true
  needs:
    - deploy-review-pcf
  environment:
    name: review/px-npe02a/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    action: stop
    deployment_tier: development
  artifacts:
    paths:
      - apps
