include:
  - project: tmobile/templates
    file:
      - /gitlab-ci/.tmo.global.common.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.pcf.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.helm-deploy.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.newman.gitlab-ci.yml

stages:
    - tmo
    - test
    - deploy
    - verify
    - destroy

variables:
  # PCF_CLI_VERSION: "6.49.0"
    PCF_ORG: "Continuous-Delivery-Platform"
    BUILDPACK: "java_buildpack_offline"
    PCF_INSTANCES: "1"
    PCF_ROUTE_HOSTNAME: "helloworld"
    PCF_BG_STRATEGY: "GREEN_AUTO_SWITCH"
    PCF_SPACE: $CI_ENVIRONMENT_TIER
    PCF_TLOGGER: "true"

.deploy: &deploy
  extends: .pcf-deploy
  stage: deploy
  resource_group: $CI_JOB_NAME
  rules:
    - when: always

.deploy-pcf:
  <<: *deploy
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build

.sanity:
  extends: .newman_test
  stage: verify
  variables:
    HEALTH_CHK_URI: "actuator/health/liveness" 
    POSTMAN_ARGS: "--insecure"
    test_report_path: "newman/"
    qtest_info_path: "src/test/qtest_info.json"
    NEWMAN_QTEST_PUBLISH: "true"
    POSTMAN_COLLECTION: "src/test"
    POSTMAN_COLLECTION_FILE: "src/test/helloworld.postman_collection.json"
    POSTMAN_ITERATIONS: "100"

.allteardown:
  extends: .pcf-teardown
  stage: destroy
  variables:
    PCF_DELETE_ALL_ROUTES_APPS: "true"
  rules:
    - if: $DELETE_ALL == "true" #only topic branches
      when: manual
      allow_failure: true
    - when: never
