include:
  - project: tmobile/templates
    file:
      - /gitlab-ci/.tmo.global.common.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.pcf.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.helm-deploy.gitlab-ci.yml
      - /gitlab-ci/.tmo.function.newman.gitlab-ci.yml

stages:
    - tmo
    - test
    - deploy
    - verify

variables:
    PCF_CLI_VERSION: "6.49.0"
    PCF_ORG: "Continuous-Delivery-Platform"
    BUILDPACK: "java_buildpack_offline"
    PCF_INSTANCES: "1"
    PCF_ROUTE_HOSTNAME: "helloworld"
    PCF_BG_STRATEGY: "GREEN_AUTO_SWITCH"

.testjob:
  image: alpine
  stage: test
  script:
    - echo $CI_PROJECT_NAME

.deploy: &deploy
  extends: .pcf-deploy
  stage: deploy
  resource_group: $CI_JOB_NAME
  rules:
    - when: always

.deploy-pcf:
  <<: *deploy
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build

.deploy-pcf-review:
  <<: *deploy
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: build-non-trunk

.sanity:
  extends: .newman_test
  stage: verify
  variables:
    HEALTH_CHK_URI: "actuator/health/liveness" 
    POSTMAN_ARGS: "--insecure"
    test_report_path: "newman/"
    qtest_info_path: "src/test/qtest_info.json"
    NEWMAN_QTEST_PUBLISH: "true"
    POSTMAN_COLLECTION: "src/test"
    POSTMAN_COLLECTION_FILE: "src/test/helloworld.postman_collection.json"
    POSTMAN_ITERATIONS: "100"
