### include yaml configuration that defines an anchor named 'job_check'

include:
  - local: '/gitlab-ci/status-check/endpoint-check.yml'

################### Checking endpoints of px domains #####################

# Checking the endpoint up or not for npe02a-dev
pcf-npe02a-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe02a_dev
    - .status-check

# Checking endpoint up or not for the npe02b-dev
pcf-npe02b-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe02b_dev
    - .status-check

# Checking endpoint up or not for the npe02c-dev
pcf-npe02c-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe02c_dev
    - .status-check

# Checking endpoint up or not for the npe03a-dev
pcf-npe03a-dev:
  stage: health-check-npe
  extends:
   - .vars_px-npe03a_dev
   - .status-check

# Checking endpoint up or not for the npe03b-dev
pcf-npe03b-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe03b_dev
    - .status-check

# Checking endpoint up or not for the npe03d-dev
pcf-npe03d-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe03d_dev
    - .status-check

################### Checking endpoints of tke domains #####################

# Checking endpoint up or not for the tke npe
tke-npe1103-dev:
  stage: health-check-npe
  extends:
    - .vars_px-npe1103_dev
    - .status-check
